http:
  port: "8081"
  
sfdc:
  username: "your_username"
  password: "your_password"
  token: "your_token"
  
file:
  accountsDir: "your_path_to_APDevFundamentals4.2_studentFiles/resources"
  
db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"